//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_GlobalResources.ProjectResource", typeof(ProjectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string filter_All {
            get {
                return ResourceManager.GetString("filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормативные.
        /// </summary>
        public static string filter_Normative_CAPEX {
            get {
                return ResourceManager.GetString("filter_Normative_CAPEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите подразделение.
        /// </summary>
        public static string filter_select_title_select_division {
            get {
                return ResourceManager.GetString("filter_select_title_select_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнен.
        /// </summary>
        public static string filter_status_close {
            get {
                return ResourceManager.GetString("filter_status_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В работе.
        /// </summary>
        public static string filter_status_open {
            get {
                return ResourceManager.GetString("filter_status_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановлен.
        /// </summary>
        public static string filter_status_pause {
            get {
                return ResourceManager.GetString("filter_status_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стратегические.
        /// </summary>
        public static string filter_Strategic_CAPEX {
            get {
                return ResourceManager.GetString("filter_Strategic_CAPEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string filter_title_close {
            get {
                return ResourceManager.GetString("filter_title_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string filter_title_filters {
            get {
                return ResourceManager.GetString("filter_title_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекты не найдены.
        /// </summary>
        public static string filter_title_no_results_found {
            get {
                return ResourceManager.GetString("filter_title_no_results_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководители проектов.
        /// </summary>
        public static string filter_title_project_manager {
            get {
                return ResourceManager.GetString("filter_title_project_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус проекта.
        /// </summary>
        public static string filter_title_status {
            get {
                return ResourceManager.GetString("filter_title_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        public static string filter_title_subdivisions {
            get {
                return ResourceManager.GetString("filter_title_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статусы внедрения инвестиционных проектов.
        /// </summary>
        public static string home_menu_1_description {
            get {
                return ResourceManager.GetString("home_menu_1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CAPEX.
        /// </summary>
        public static string home_menu_1_name {
            get {
                return ResourceManager.GetString("home_menu_1_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список проектов и программ ДАТП.
        /// </summary>
        public static string home_menu_2_description {
            get {
                return ResourceManager.GetString("home_menu_2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекты.
        /// </summary>
        public static string home_menu_2_name {
            get {
                return ResourceManager.GetString("home_menu_2_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структура сопровождения инвестиционных проектов.
        /// </summary>
        public static string home_menu_3_description {
            get {
                return ResourceManager.GetString("home_menu_3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда.
        /// </summary>
        public static string home_menu_3_name {
            get {
                return ResourceManager.GetString("home_menu_3_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормативная документация .
        /// </summary>
        public static string home_menu_4_description {
            get {
                return ResourceManager.GetString("home_menu_4_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документация.
        /// </summary>
        public static string home_menu_4_name {
            get {
                return ResourceManager.GetString("home_menu_4_name", resourceCulture);
            }
        }
    }
}
