//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_GlobalResources.ProjectResource", typeof(ProjectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string filter_All {
            get {
                return ResourceManager.GetString("filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормативные.
        /// </summary>
        public static string filter_Normative_CAPEX {
            get {
                return ResourceManager.GetString("filter_Normative_CAPEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите департамент.
        /// </summary>
        public static string filter_select_title_select_departmen {
            get {
                return ResourceManager.GetString("filter_select_title_select_departmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите подразделение.
        /// </summary>
        public static string filter_select_title_select_division {
            get {
                return ResourceManager.GetString("filter_select_title_select_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнен.
        /// </summary>
        public static string filter_status_close {
            get {
                return ResourceManager.GetString("filter_status_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В работе.
        /// </summary>
        public static string filter_status_open {
            get {
                return ResourceManager.GetString("filter_status_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановлен.
        /// </summary>
        public static string filter_status_pause {
            get {
                return ResourceManager.GetString("filter_status_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стратегические.
        /// </summary>
        public static string filter_Strategic_CAPEX {
            get {
                return ResourceManager.GetString("filter_Strategic_CAPEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string filter_title_close {
            get {
                return ResourceManager.GetString("filter_title_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Департаменты.
        /// </summary>
        public static string filter_title_department {
            get {
                return ResourceManager.GetString("filter_title_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string filter_title_filters {
            get {
                return ResourceManager.GetString("filter_title_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекты не найдены.
        /// </summary>
        public static string filter_title_no_results_found {
            get {
                return ResourceManager.GetString("filter_title_no_results_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководители проектов.
        /// </summary>
        public static string filter_title_project_manager {
            get {
                return ResourceManager.GetString("filter_title_project_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделения.
        /// </summary>
        public static string filter_title_select_division {
            get {
                return ResourceManager.GetString("filter_title_select_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус проекта.
        /// </summary>
        public static string filter_title_status {
            get {
                return ResourceManager.GetString("filter_title_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        public static string filter_title_subdivisions {
            get {
                return ResourceManager.GetString("filter_title_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статусы внедрения инвестиционных проектов.
        /// </summary>
        public static string home_menu_1_description {
            get {
                return ResourceManager.GetString("home_menu_1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string home_menu_1_name {
            get {
                return ResourceManager.GetString("home_menu_1_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список ваших проектов..
        /// </summary>
        public static string home_menu_2_description {
            get {
                return ResourceManager.GetString("home_menu_2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекты.
        /// </summary>
        public static string home_menu_2_name {
            get {
                return ResourceManager.GetString("home_menu_2_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структура сопровождения инвестиционных проектов.
        /// </summary>
        public static string home_menu_3_description {
            get {
                return ResourceManager.GetString("home_menu_3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда.
        /// </summary>
        public static string home_menu_3_name {
            get {
                return ResourceManager.GetString("home_menu_3_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормативная документация .
        /// </summary>
        public static string home_menu_4_description {
            get {
                return ResourceManager.GetString("home_menu_4_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документация.
        /// </summary>
        public static string home_menu_4_name {
            get {
                return ResourceManager.GetString("home_menu_4_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти....
        /// </summary>
        public static string home_menu_link {
            get {
                return ResourceManager.GetString("home_menu_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бюджет\Контракт.
        /// </summary>
        public static string title_budget_contract {
            get {
                return ResourceManager.GetString("title_budget_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бюджет проекта.
        /// </summary>
        public static string title_budget_project {
            get {
                return ResourceManager.GetString("title_budget_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бюджет:.
        /// </summary>
        public static string title_budget_value {
            get {
                return ResourceManager.GetString("title_budget_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПНР (контракт).
        /// </summary>
        public static string title_contract_commissioning {
            get {
                return ResourceManager.GetString("title_contract_commissioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПНР (контракт):.
        /// </summary>
        public static string title_contract_commissioning_value {
            get {
                return ResourceManager.GetString("title_contract_commissioning_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМР (контракт).
        /// </summary>
        public static string title_contract_construction {
            get {
                return ResourceManager.GetString("title_contract_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМР (контракт):.
        /// </summary>
        public static string title_contract_construction_value {
            get {
                return ResourceManager.GetString("title_contract_construction_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контракт детально.
        /// </summary>
        public static string title_contract_detali {
            get {
                return ResourceManager.GetString("title_contract_detali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инжиниринг (контракт).
        /// </summary>
        public static string title_contract_engineering {
            get {
                return ResourceManager.GetString("title_contract_engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инжиниринговые работы (контракт):.
        /// </summary>
        public static string title_contract_engineering_value {
            get {
                return ResourceManager.GetString("title_contract_engineering_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оборудование (контракт).
        /// </summary>
        public static string title_contract_equipment {
            get {
                return ResourceManager.GetString("title_contract_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость оборудования (контракт):.
        /// </summary>
        public static string title_contract_equipment_value {
            get {
                return ResourceManager.GetString("title_contract_equipment_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие работы (контракт).
        /// </summary>
        public static string title_contract_other {
            get {
                return ResourceManager.GetString("title_contract_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие затраты (контракт):.
        /// </summary>
        public static string title_contract_other_value {
            get {
                return ResourceManager.GetString("title_contract_other_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма по контракту.
        /// </summary>
        public static string title_contract_project {
            get {
                return ResourceManager.GetString("title_contract_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контракт:.
        /// </summary>
        public static string title_contract_value {
            get {
                return ResourceManager.GetString("title_contract_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        public static string title_currency {
            get {
                return ResourceManager.GetString("title_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string title_email {
            get {
                return ResourceManager.GetString("title_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string title_email_performer {
            get {
                return ResourceManager.GetString("title_email_performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (en).
        /// </summary>
        public static string title_en {
            get {
                return ResourceManager.GetString("title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цели:.
        /// </summary>
        public static string title_goals_project {
            get {
                return ResourceManager.GetString("title_goals_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цели внедрения проекта (en):.
        /// </summary>
        public static string title_goals_project_en {
            get {
                return ResourceManager.GetString("title_goals_project_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цели внедрения проекта (ru):.
        /// </summary>
        public static string title_goals_project_ru {
            get {
                return ResourceManager.GetString("title_goals_project_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон:.
        /// </summary>
        public static string title_mobil_phone {
            get {
                return ResourceManager.GetString("title_mobil_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string title_name {
            get {
                return ResourceManager.GetString("title_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель:.
        /// </summary>
        public static string title_name_boss_performer {
            get {
                return ResourceManager.GetString("title_name_boss_performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подрядная организация:.
        /// </summary>
        public static string title_name_performer {
            get {
                return ResourceManager.GetString("title_name_performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проект:.
        /// </summary>
        public static string title_name_project {
            get {
                return ResourceManager.GetString("title_name_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название проекта (en):.
        /// </summary>
        public static string title_name_project_en {
            get {
                return ResourceManager.GetString("title_name_project_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название проекта (ru):.
        /// </summary>
        public static string title_name_project_ru {
            get {
                return ResourceManager.GetString("title_name_project_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество:.
        /// </summary>
        public static string title_patronymic {
            get {
                return ResourceManager.GetString("title_patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПНР(факт).
        /// </summary>
        public static string title_payment_commissioning {
            get {
                return ResourceManager.GetString("title_payment_commissioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПНР (факт):.
        /// </summary>
        public static string title_payment_commissioning_value {
            get {
                return ResourceManager.GetString("title_payment_commissioning_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМР (факт).
        /// </summary>
        public static string title_payment_construction {
            get {
                return ResourceManager.GetString("title_payment_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМР (факт):.
        /// </summary>
        public static string title_payment_construction_value {
            get {
                return ResourceManager.GetString("title_payment_construction_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата детально.
        /// </summary>
        public static string title_payment_detali {
            get {
                return ResourceManager.GetString("title_payment_detali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инжиниринг (факт).
        /// </summary>
        public static string title_payment_engineering {
            get {
                return ResourceManager.GetString("title_payment_engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инжиниринговые работы (факт):.
        /// </summary>
        public static string title_payment_engineering_value {
            get {
                return ResourceManager.GetString("title_payment_engineering_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оборудование (факт).
        /// </summary>
        public static string title_payment_equipment {
            get {
                return ResourceManager.GetString("title_payment_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость оборудования (факт):.
        /// </summary>
        public static string title_payment_equipment_value {
            get {
                return ResourceManager.GetString("title_payment_equipment_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие работы (факт).
        /// </summary>
        public static string title_payment_other {
            get {
                return ResourceManager.GetString("title_payment_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие затраты (факт):.
        /// </summary>
        public static string title_payment_other_value {
            get {
                return ResourceManager.GetString("title_payment_other_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон руководителя:.
        /// </summary>
        public static string title_phone_boss_performer {
            get {
                return ResourceManager.GetString("title_phone_boss_performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон:.
        /// </summary>
        public static string title_phone_performer {
            get {
                return ResourceManager.GetString("title_phone_performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контракт\Оплата.
        /// </summary>
        public static string title_plan_fact {
            get {
                return ResourceManager.GetString("title_plan_fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Затраты.
        /// </summary>
        public static string title_project_budget {
            get {
                return ResourceManager.GetString("title_project_budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказчик:.
        /// </summary>
        public static string title_project_customer {
            get {
                return ResourceManager.GetString("title_project_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о проекте.
        /// </summary>
        public static string title_project_info {
            get {
                return ResourceManager.GetString("title_project_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный от ДАТП.
        /// </summary>
        public static string title_project_manager {
            get {
                return ResourceManager.GetString("title_project_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string title_project_manager_email {
            get {
                return ResourceManager.GetString("title_project_manager_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО:.
        /// </summary>
        public static string title_project_manager_fio {
            get {
                return ResourceManager.GetString("title_project_manager_fio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон:.
        /// </summary>
        public static string title_project_manager_phone_mobile {
            get {
                return ResourceManager.GetString("title_project_manager_phone_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий телефон:.
        /// </summary>
        public static string title_project_manager_phone_work {
            get {
                return ResourceManager.GetString("title_project_manager_phone_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прооект:.
        /// </summary>
        public static string title_project_name {
            get {
                return ResourceManager.GetString("title_project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исполнитель работ.
        /// </summary>
        public static string title_project_performer {
            get {
                return ResourceManager.GetString("title_project_performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаги выполнения проекта.
        /// </summary>
        public static string title_project_steps {
            get {
                return ResourceManager.GetString("title_project_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (ru).
        /// </summary>
        public static string title_ru {
            get {
                return ResourceManager.GetString("title_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СПП-элемент:.
        /// </summary>
        public static string title_spp_element {
            get {
                return ResourceManager.GetString("title_spp_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СПП-элемент\Владелец строки:.
        /// </summary>
        public static string title_spp_element_owner {
            get {
                return ResourceManager.GetString("title_spp_element_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец строки:.
        /// </summary>
        public static string title_spp_owner {
            get {
                return ResourceManager.GetString("title_spp_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начат:.
        /// </summary>
        public static string title_start_project {
            get {
                return ResourceManager.GetString("title_start_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус проекта:.
        /// </summary>
        public static string title_status_project {
            get {
                return ResourceManager.GetString("title_status_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончание согласно контракта:.
        /// </summary>
        public static string title_stop_project {
            get {
                return ResourceManager.GetString("title_stop_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структурное подразделение:.
        /// </summary>
        public static string title_structural_subdivisions {
            get {
                return ResourceManager.GetString("title_structural_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма на ПНР.
        /// </summary>
        public static string title_summ_commissioning {
            get {
                return ResourceManager.GetString("title_summ_commissioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма на СМР.
        /// </summary>
        public static string title_summ_construction {
            get {
                return ResourceManager.GetString("title_summ_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма на инжиниринг.
        /// </summary>
        public static string title_summ_engineering {
            get {
                return ResourceManager.GetString("title_summ_engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма на оборудование.
        /// </summary>
        public static string title_summ_equipment {
            get {
                return ResourceManager.GetString("title_summ_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма на другие затраты.
        /// </summary>
        public static string title_summ_other {
            get {
                return ResourceManager.GetString("title_summ_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамиля:.
        /// </summary>
        public static string title_surname {
            get {
                return ResourceManager.GetString("title_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип проекта:.
        /// </summary>
        public static string title_type_project {
            get {
                return ResourceManager.GetString("title_type_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий телефон:.
        /// </summary>
        public static string title_work_phone {
            get {
                return ResourceManager.GetString("title_work_phone", resourceCulture);
            }
        }
    }
}
